CREATE TABLE `timingtrace` (
	`id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
    	`employeeId` BIGINT(20) UNSIGNED NOT NULL,
	`employeeName` VARCHAR(255) NOT NULL,
	`register` DATETIME NOT NULL,
	`source` ENUM('SYS','MAN') NOT NULL,
	`is_active` BIT(1) NOT NULL DEFAULT b'1',
	`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`created_by` BIGINT(20) UNSIGNED NOT NULL DEFAULT '0',
	`updated_by` BIGINT(20) UNSIGNED NOT NULL DEFAULT '0',
	PRIMARY KEY (`id`) USING BTREE,
	INDEX `created_by` (`created_by`) USING BTREE,
	INDEX `updated_by` (`updated_by`) USING BTREE,
    	CONSTRAINT `fk_employeeId_users` FOREIGN KEY (`employeeId`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
	INDEX `is_active` (`is_active`) USING BTREE
)
COLLATE='utf8mb4_unicode_ci'
ENGINE=InnoDB
AUTO_INCREMENT=0;