CREATE TABLE `products` (
	`id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
    `nome` VARCHAR(255) NOT NULL,
	`sku` VARCHAR(255) NOT NULL COMMENT 'unique',
	`type` ENUM('SIMPLE','COMPOSITE','INGREDIENT') NOT NULL,
	`uom` VARCHAR(255) NOT NULL COMMENT 'ex: un, g, ml',
	`picture` VARCHAR(2000) NOT NULL,
	`is_sellable` BOOL NOT NULL,
	`sale_price` DECIMAL(10,2) NULL,
	`is_active` BIT(1) NOT NULL DEFAULT b'1',
	`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`created_by` BIGINT(20) UNSIGNED NOT NULL DEFAULT '0',
	`updated_by` BIGINT(20) UNSIGNED NOT NULL DEFAULT '0',
	PRIMARY KEY (`id`) USING BTREE,
	INDEX `created_by` (`created_by`) USING BTREE,
	INDEX `updated_by` (`updated_by`) USING BTREE,
    
	INDEX `is_active` (`is_active`) USING BTREE
)
COLLATE='utf8mb4_unicode_ci'
ENGINE=InnoDB
AUTO_INCREMENT=0;